### ISSUE TITLE
[Chapter 11] Tensorboard can't find event files

### ISSUE THREAD

**Issue by kareemamrr** [ageron/handson-ml2#127] opened 2020-03-23 13:33 UTC
Chapter 11 exercise 8-b), running the notebook code, Tensorboard fails to see find my event files, yet the necessary subdirectories and event files are all generated. Anybody knows what's wrong?

**Comment by ageron** [comment] 2020-04-01 09:01
Hi @kareemamrr ,
Thanks for your feedback. I'm sorry, but I don't think I've ever run into this problem before, and I can't reproduce it.

One possibility is that tensorboard is not running in the same directory as Jupyter, for some reason? If this is the case, then perhaps replacing the relative paths with absolute paths should help.

Or else, it might be a versioning problem: make sure you are using the latest version of tensorflow and tensorboard. Perhaps try uninstalling all versions of tensorboard (in my case, during my tests I sometimes installed the nightly version, so make sure to uninstall all version, with `pip uninstall tensorboard`, `pip uninstall tb-nightly`, or using conda if that's what you're using). Then reinstall the latest version (`pip install -U tensorboard`), and restart Jupyter and the notebook.

Or perhaps there's something wrong with the filesystem, or maybe some of the even files are corrupted? Perhaps try removing the log directory (of course, back it up before removing it, if you want), and then try again.

Hope this helps.

**Comment by kareemamrr** [comment] 2020-04-01 17:11
It did help. Thank you!

**Comment by ageron** [comment] 2020-04-01 21:25
Hi @kareemamrr ,
I'm glad it did. Could please explain what solved the issue, in case someone else runs it? Thanks!

**Comment by kareemamrr** [comment] 2020-04-01 21:46
It was a problem with the relative path as you suggested. Could I ask what is value in adding `./`  using `os.curdir` to the log_dir path as well as in the call to tensorboard, does it make any difference?

**Comment by ageron** [comment] 2020-04-02 00:14
Thanks for your feedback.
I think there used to be a bug where `"my_logs"` would fail (I can't remember whether it was when running the TensorBoard plugin or when starting the TensorBoard server) but `"./my_logs"` would work. Since the path is `"./my_logs"` on MacOSX and Linux, but it's ".\my_logs" on Windows, I wrote `os.path.join(".", "my_logs")` instead, to make the code portable. And just for the sake of being explicit, I replaced `"."` with `os.curdir`. But it seems that this is not needed anymore, so feel free to remove it.
Closing this issue. Thanks again for your feedback.

**Closed by ageron** 2020-04-02 00:14 UTC
