### ISSUE TITLE
03_classificatio - ConvergenceWarning

### ISSUE THREAD

**Issue by TheMaybemachine** [ageron/handson-ml2#75] opened 2019-12-17 09:58 UTC
When I try to run:
```
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train.astype(np.float64))
cross_val_score(sgd_clf, X_train_scaled, y_train, cv=3, scoring="accuracy")
```
I get 
```
C:\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
```
I never get a result, it gets stuck.

**Comment by satya400** [comment] 2019-12-31 07:00
When ever I get convergence warning, I could get over it by setting max_iter / n_iter to a bigger number like 5000.  Please see if this helps you.

Thanks
Satya

**Comment by hopezh** [comment] 2019-12-31 08:48
Hi @satya400 , I just encountered the same  warning as shown below. May I ask **_how to change max_iter / n_iter_** as you suggested? It seems that _**max_iter**_ is not a parameter for the StandardScaler() or cross_val_score() functions. 

```
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
```

**Comment by satya400** [comment] 2019-12-31 09:23
Hi @hopezh , the sgd_clf has this max_iter parameter and its default is 1000. Please try with 5000 to see if it converges.

**Comment by ageron** [comment] 2020-03-31 02:40
I'm assuming the issue is resolved? Closing this issue, but please feel free to reopen it if the problem persists.

**Closed by ageron** 2020-03-31 02:40 UTC
