### ISSUE TITLE
Chapter 2 -  Doubt 

### ISSUE THREAD

**Issue by 2807754** [ageron/handson-ml2#185] opened 2020-06-12 21:06 UTC
Hello community,

I started with this interesting book and this error have presented once I introduce the following code:

%matplotlib inline 
 import matplotlib.pyplot as plt 
housing.hist(bins=50, figsize=(20,15)) plt.show()

once deployed it showed this: 

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-13-5afef84f365d> in <module>
----> 1 get_ipython().run_line_magic('matplotlib', 'inline')
      2 import matplotlib.pyplot as plt
      3 housing.hist(bins=50, figsize=(20,15))
      4 plt.show()

/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py in run_line_magic(self, magic_name, line, _stack_depth)
   2305                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2306             with self.builtin_trap:
-> 2307                 result = fn(*args, **kwargs)
   2308             return result
   2309 

</opt/anaconda3/lib/python3.7/site-packages/decorator.py:decorator-gen-108> in matplotlib(self, line)

/opt/anaconda3/lib/python3.7/site-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

/opt/anaconda3/lib/python3.7/site-packages/IPython/core/magics/pylab.py in matplotlib(self, line)
     97             print("Available matplotlib backends: %s" % backends_list)
     98         else:
---> 99             gui, backend = self.shell.enable_matplotlib(args.gui.lower() if isinstance(args.gui, str) else args.gui)
    100             self._show_matplotlib_backend(args.gui, backend)
    101 

/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py in enable_matplotlib(self, gui)
   3405                 gui, backend = pt.find_gui_and_backend(self.pylab_gui_select)
   3406 
-> 3407         pt.activate_matplotlib(backend)
   3408         pt.configure_inline_support(self, backend)
   3409 

/opt/anaconda3/lib/python3.7/site-packages/IPython/core/pylabtools.py in activate_matplotlib(backend)
    304 
    305     import matplotlib
--> 306     matplotlib.interactive(True)
    307 
    308     # Matplotlib had a bug where even switch_backend could not force

AttributeError: module 'matplotlib' has no attribute 'interactive'

many thanks for your help

**Comment by uzair-suria** [comment] 2020-06-14 18:39
Please take a look at [issue 11821](https://github.com/ipython/ipython/issues/11821#issuecomment-511555539). You might need to uninstall and then re-install matplotlib using conda.
To remove matplotlib:
`conda remove --force matplotlib`

According to official [conda docs](https://docs.conda.io/projects/conda/en/latest/commands/remove.html) the `--force` modifier:

> Forces removal of a package without removing packages that depend on it. Using this option will usually leave your environment in a broken and inconsistent state.

To reinstall:
`conda install -c conda-forge matplotlib`

Having said that, I would strongly advise you to use the instructions provided in the book to create a virtual environment using `pip`. This way there will be no doubts when following projects in this book

**Comment by guruboy001** [comment] 2020-06-14 18:43
You could simply use google collab. It will save you the stress of setting up the environment

**Comment by chaitanya3323** [comment] 2020-08-07 15:30
Try first importing matpotlib and then use the statement:
%matplotlib inline

**Comment by Aliiiu** [comment] 2021-01-31 23:14
pls I'm having svd related error while trying to fit the LinAlg model. pls what can be wrong

**Comment by ageron** [comment] 2021-03-11 03:18
Hi @2807754,
I'm assuming you fixed the matplotlib installation issue? The answers above are correct.
Closing this issue, but please feel free to reopen it if the problem is not resolved.

@Aliiiu could you please open a separate issue and provide more details (including the exact code you ran and the stacktrace of the error you got)?

**Closed by ageron** 2021-03-11 03:18 UTC
