### ISSUE TITLE
ch. 2: missing inplace=True in drop/dropna?

### ISSUE THREAD

**Issue by notestaff** [ageron/handson-ml2#126] opened 2020-03-23 00:13 UTC
In Ch.  2 section on Data Cleaning,

`housing.dropna(subset=["total_bedrooms"])    # option 1`
`housing.drop("total_bedrooms", axis=1)       # option 2`

seems to need `inplace=True`? @ageron

**Comment by notestaff** [comment] 2020-03-23 00:17
(I see now, option 1 and option 2 are _meant_ to be no-ops)

**Comment by ageron** [comment] 2020-04-01 08:52
Hi @notestaff ,
Thanks for your feedback. Indeed, I just wanted to show various options, but I only actually applied one of them.
Closing this issue, but feel free to reopen if it's still unclear.

**Closed by ageron** 2020-04-01 08:52 UTC

**Comment by notestaff** [comment] 2020-04-01 14:06
@ageron The confusing part is that two of the options shown can't be used as written, because as written they're no-ops.  Maybe, write each option functional-style (`housing = housing.dropna(subset=["total_bedrooms"])`) rather than in-place, then the last option still prevails but they can all be used verbatim?

Thanks for your excellent book.

**Comment by AlessandroMiola** [comment] 2020-09-24 21:04
Hi @ageron, @notestaff,
I'm interested in understanding this better. @notestaff provided that I'm fully getting your point, imo the way they are written poses no problems as the implicit inplace=False returns a copy of housing.
On the other end, `housing["total_bedrooms"].fillna(median, inplace=True)` is giving me a _SettingWithCopyWarning_ due to chained indexing, that could be possibly avoided by writing `housing["total_bedrooms"] = housing["total_bedrooms"].fillna(median)` (though I do understand that this does not really affect what was intended to be shown here).

Thank you for the amazing book and for your answer.
